### PR TITLE
Remove hackney logo, add a header specific to this service

### PR DESCRIPTION
**Pull request by wrightmartin**
- [x] Where shall we link the feedback link to?

### CODE REVIEW

**Comment by garethrees** [comment]
`clientsupport-council-foi@mysociety.org`

**Comment by wrightmartin** [comment]
Screenshot 2019-04-15 at 09 08 15

**Review by garethrees — APPROVED** [review]
Nice 👍 

Can probably squash these two commits.

Might also be worth adding the "under construction" banner that we used in https://mysociety.github.io/hackney-foi-prototype/?

https://github.com/mysociety/hackney-foi-prototype/blob/master/_sass/_hackney-admin.scss#L1-L9

**Comment by wrightmartin** [comment]
Done 🇹🇭

**Comment by wrightmartin** [comment]
Merged https://github.com/mysociety/foi-self-assessment/commit/33fcda22a999f49b153f76a299055445c7f72be4

**Pull request closed without merging**
